### ISSUE TITLE
Platformer2D Touch Input

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame.Samples#10]
It seems the Platformer2D sample depends on GamePad working on touch devices to control player movement.  This breaks down on Windows Phone or Windows 8 tablets where a virtual thumb sticks implementation doesn't exist yet.

Should we add explicit support for touch input?  Or should we implement virtual thumb sticks for these platforms?

**Comment by SimonDarksideJ** [comment]
As I've now found my touch input controls @tomspilman it would be a fairly easy job to port this in to the Platformer project.

Currently it's controlled by either keys or accelerometer + tap to jump.  Gamepad is still there from it's XBOX days.

I'll add it to the todo list

**Comment by SimonDarksideJ** [comment]
As discussed earlier, it would be nice to have a generic input control system (probably as a NuGet) that we could use for all the samples.
Also on the todo list :D. The spacewar sample is the furthest along with that, so that will likely be the beginning.

**Comment by tomspilman** [comment]
> it would be nice to have a generic input control system 

The samples need to remain focused on MonoGame and being self contained.  We really shouldn't have another helper library it depends on.  Build the functionality into the sample.

**Comment by SimonDarksideJ** [comment]
OK, fair enough.  Although planning for the same code "hopefully2 to be used for at least all the samples I do.

**Comment by tomspilman** [comment]
I think we can assume the code will be shared among all the samples and hopefully pretty minimal focusing just on what the samples we have need.

I just cannot stand samples that are over engineered.  Samples should be very simple to modify and experiment with.

**Comment by danzel** [comment]
Have started on this in https://github.com/danzel/MonoGame.Samples/tree/virtual-gamepad

Looks like this:
![image](https://cloud.githubusercontent.com/assets/393086/2868720/0c984ffc-d24d-11e3-8d8e-c3aedb17822b.png)

Should finish it off later this weekend hopefully.

**Comment by tomspilman** [comment]
So is this considered done then?

**Comment by danzel** [comment]
I'd say so
