### ISSUE TITLE
Spacewar sample disappeared?

### ISSUE THREAD

**Issue by SimonDarksideJ** [MonoGame/MonoGame.Samples#16]
@tomspilman not sure what's happened by the files for the Spacewar sample have disappeared from the develop branch?

Odd because that PR was merged a while ago, before NeonShooter.

Should I resubmit the PR for that?
Odd thing is that the .SLN files still point to the missing folder?

**Comment by tomspilman** [comment]
You closed that PR...

https://github.com/Mono-Game/MonoGame.Samples/pull/11

... I assumed you meant to do that. :)

**Comment by SimonDarksideJ** [comment]
That is odd, I thought I only closed it after it was merged.  I'll resubmit then

**Comment by SimonDarksideJ** [comment]
Actually @tomspilman , just looked in the closed  PR List and it was merged?
https://github.com/Mono-Game/MonoGame.Samples/pull/13

Ideas?

**Comment by tomspilman** [comment]
It seems that in https://github.com/Mono-Game/MonoGame.Samples/pull/12 you renamed and/or deleted a bunch of SpaceWar stuff.  Maybe you made a mistake when copying the one sample to make the other?

**Comment by SimonDarksideJ** [comment]
Not sure at this point, in any case I've resubmitted the spacewar sample as a new PR based on the current develop branch
