### ISSUE TITLE
Were the Android / Ouya view changes committed standalone to the samples develop repo?

### ISSUE THREAD

**Issue by SimonDarksideJ** [MonoGame/MonoGame.Samples#18]
Originally spotted in " response to Update android/ouya activity files to work with mono/MonoGame#2393 "

@danzel any ideas?

**Comment by danzel** [comment]
Yep, I did this in #3 :)

**Comment by SimonDarksideJ** [comment]
Great just checking since the SpaceWar sample had a bit of confusion.

Reminds me I need to get the Project templates for iOS \ Android and Mac OS in to the MonoGame NuGet to support the new platforms in the .Binaries packaes.  Will ensure to include these changes
