### ISSUE TITLE
Build errors in VS2013 

### ISSUE THREAD

**Issue by ccsevers** [MonoGame/MonoGame.Samples#20]
Hi,
My guess is that I'm missing some important step in getting started. I imported the project in VS2013 and when I try and build I get 50 errors, all like:

```
 Error  46  Could not copy the file 
"F:\git\MonoGame.Samples\ContentBuilder\bin\Windows\Content\Tiles\Platform.xnb" because it was not found.   
Platformer2D
```

I followed the instructions here (http://msxna.codeplex.com/releases/view/117230) but no luck. I can see .xnb files in the VS Solution Explorer window but clicking on them gives a file not found error. 

I understand everyone is busy getting things into this repo but a very simple walkthrough on how to start from zero would be really helpful. 

Thanks,
Chris

**Comment by ccsevers** [comment]
Okay tracked down the problem. First I needed to build the Content project and then that failed with a more informative error message that I was missing MonoGame.ContentPipeline.targets in the right place. After I installed that from the base MonoGame package I was able to build Content and then build WindowsGL. 

Shall I update the readme or make a getting started wiki in case I'm not the only one?

**Comment by ccsevers** [comment]
Looks like this is all doable with nuget. I submitted a pull #21

**Comment by SimonDarksideJ** [comment]
Hmm,
All the samples should be using NuGet where they can, this includes the Content Project.

The Content Projects should have the MonoGame.Framework.ContentProject NuGet installed (then excluding the packages.config from the csproj) in the Content Project (not builder).  This adds the MonoGameContentProcessors to the content solution.

Yes, you need to build the content first before building each sample.  If the Read-me isn't clear I'll get that sorted :dancer: 

There is an issue raised already about putting full docs in for each sample, just need to find the time to get that sorted.

**Comment by SimonDarksideJ** [comment]
Can this be closed now?
P.S. I also updated the packages recently for the latest NuGet release
