### ISSUE TITLE
Project type not supported by MonoDevelop

### ISSUE THREAD

**Issue by darkoverlordofdata** [MonoGame/MonoGame.Samples#23]
The samples build ok. But they get a slew of run time errors like this one - Cannot copy /home/bruce/Git/MonoGame.Samples/ContentBuilder/bin/Linux/Content/Backgrounds/Layer0_0.xnb to /home/bruce/Git/MonoGame.Samples/Platformer2D/bin/Linux/Debug/Content/Backgrounds/Layer0_0.xnb, as the source file doesn't exist....

So I assume I have to use the Samples-Content project to convert the png's to xnb's. But it doesn't open, there is a popup message: 

Could not load project 'Platformer2D/Content/Platformer2D.contentproj' with unknown item type '{96E2B04D-8817-42c6-938A-82C39BA4D311}'

I'm on Linux Mint 16, mono version 3.2.1, monodevelop version 5.1

**Comment by darkoverlordofdata** [comment]
Ah - I found the issue. That's the guid for the MonoGame addin. It appears that even though it compiles in 5.1, it doesn't mean that it actually works in 5.1.  That is the current master branch, so what is the latest branch of MonoDevelop that MonoGame actually works on?

**Comment by KonajuGames** [comment]
MonoDevelop is still 4.1, correct?

The add-on hasn't received many updates for a while now.

**Comment by darkoverlordofdata** [comment]
You know what? Never mind. I've come to the conclusion that monogame on linux is so out of sync and bugy that it's not worth my time. I have other project that are more fruitful. It's too bad, too. I can get mvc4 running great on mono. I'll stick to developing my game on html5.
