### ISSUE TITLE
IOS sample multiple issues

### ISSUE THREAD

**Issue by gomski** [MonoGame/MonoGame.Samples#24]
Hi folks,

I have just started to try MonoGame for some fun projects and I like it a lot so far.
First thing to do is learning by reading and get a grip on how things are working by reading existing code, so your samples were are nice place to get some compressed and skillful overview ranging over all platforms.
To assure myself that MG is really working an all platforms I decided to test your samples on every platform I can get reach of.
I was lucky with everything except of the OUYA and PSM solution because of a lack of hardware. All windows and android based stuff was working well right out of the box.
Last but not least I tried the IOS solution and have some issues with it.
1. monogame.png was not copied to output directed > changed the props accordingly
2. Fonts\Hud could not be loaded > reseted the props without changing them
3. Font is not rendered correctly, changed the processor to MGSprintFont but this does not help > no solution for this so far... 

Here is my dev platform:
MacOs Mavericks with a Window 8.1 Box running in Parallels or native.
I have got a Xamarin IOS and Android License.
Visuals Studio 2013 is compiling the IOS stuff through the Xamarin.IOS build host.
MonoGame was installed with the actual binaries but I have also cloned the git. Samples are cloned via git... just trying to send a commit with my changes ;)

**Comment by gomski** [comment]
I figured out 2 possible issues...
1. Changed the content processor to MonoGame SpriteFont for Fonts\Hud
2. Added <Import Project="C:\GameProjects\MonoGame\MonoGame.ContentPipeline\MonoGame.ContentPipeline.targets" /> to content project; now i can see the line 1>  MonoGame Platform %CHOSEN PLATFORM% in my output window when building the content solution

both fixed the rendering of the font on iOS

**Comment by SimonDarksideJ** [comment]
If you want to submit a PR with your fixes (be sure to test all platforms again before committing) , we can review it and update the samples.
Just be sure to commit your changes to a new branch from the develop branch before submitting a pr back to the develop branch.

thanks for testing this, we have had all these platforms tested, but iOS and Mac systems seem to vary so more testing is good.

Feel free to try and contribute to the rest of the sample as well if you have time :D

**Comment by SimonDarksideJ** [comment]
Note, all the samples have been updated to use the new MGCB tool in the latest PR.  This should sort out most of the issues above.

**Comment by SimonDarksideJ** [comment]
@gomski can this issue now be closed?

**Comment by SimonDarksideJ** [comment]
Closed due to no response
