### ISSUE TITLE
Make Develop The Default Branch

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame.Samples#27]
Should we make the `develop` branch of this repo the default like we do with MonoGame?  I've had one person that was confused why the samples didn't work for them...  they were trying to use the `master` branch samples with the `develop` branch on GitHub.

Any other way we could clear up this confusion?

@KonajuGames @DDReaper ??

**Comment by SimonDarksideJ** [comment]
Interesting debate @tomspilman 
I'd say making develop the default branch is fair for devs, however it would need to be made clear in the readme as to the alignment.

Master = Full releases - Current 3.2 build
develop - dev dreleases - against current source / nuget's

**Comment by tomspilman** [comment]
> I'd say making develop the default branch is fair for devs

It would make things consistent with the main MonoGame repo at least.  I would assume most people that end up here would be people that are already working directly from source code anyway.

> however it would need to be made clear in the readme as to the alignment.

Sure... we can get something in there.

**Comment by SimonDarksideJ** [comment]
Any update on this @tomspilman , can we make "develop" the default branch (certainly stops annoying things, like when you submit a PR :S)

**Comment by tomspilman** [comment]
Done.
