### ISSUE TITLE
Improve documentation for building samples on major desktop platforms

### ISSUE THREAD

**Issue by eindoofus** [MonoGame/MonoGame.Samples#36]
The MonoGame ecosystem isn't too large and the IDEs are fairly limited between different platforms. For someone entering game development they're more likely to tackle desktop development first due to the stability of the medium. 

Having a walk-through on how to build a sample projects on different desktop platforms would be a big morale booster for new game developers, especially when they're able to see the same sample running on different OSes.

**Comment by SimonDarksideJ** [comment]
Please refer to the main MonoGame documentation for building projects
https://docs.monogame.net/articles/packaging_games.html
