### ISSUE TITLE
Mac Sample build configuration issues

### ISSUE THREAD

**Issue by andykorth** [MonoGame/MonoGame.Samples#37]
There seem to be some configuration issues getting the samples to work on a Mac.

I'm opening the project in Xamarin Studio 5.5.4, which should be the latest, right now.

The sample project has build configurations set up, but the configuration mappings had each target turned off. http://kortham.net/temp/upshot_JnbZVKkW.png These boxes should all be checked for each of the four configuration options. 

I had to manually add the references to the two projects, so they would be included int he Platformer2D build: http://kortham.net/temp/upshot_v2gAJL3m.png

Don't forget to pull your git submodules or you'll have a missing OpenTK file ;) I figured that one out!

The debug configuration mode defines the symbols `DEBUG MONOMAC`, but the release build configuration doesn't define `MONOMAC`. It probably should. http://kortham.net/temp/upshot_Jb7ogcEB.png

This issue is a followup to https://github.com/mono/MonoGame/issues/1043

**Comment by SimonDarksideJ** [comment]
If you are on mac, do you want to try adding the new 3.3 MacOS NuGet package and see if that resolves your issue?

**Comment by SimonDarksideJ** [comment]
Updated and tested with MonoGame 3.8 with new samples
