### ISSUE TITLE
Implement Windows DirectX

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame.Samples#4]
We have a Windows desktop OpenGL sample, but we don't have a sample for DirectX on Windows desktop.

**Comment by tomspilman** [comment]
FYI @DDReaper

**Comment by SimonDarksideJ** [comment]
Last commit missed the .sln file for the DX samples. corrected.

This issue should not be closed

**Comment by SimonDarksideJ** [comment]
@tomspilman do you want to merge the missing file so we can close this request?

**Comment by tomspilman** [comment]
Sorry... busy morning.  All done.
