### ISSUE TITLE
Microsoft.Xna.Framework.Graphics Missing

### ISSUE THREAD

**Issue by NVentimiglia** [MonoGame/MonoGame.Samples#40]
Just tried booting up the examples. DId a nuget restore. Microsoft.Xna.Framework.Graphics; is missing all over the place. Using MonoGame 3.3 on Windows Visual Studio 2013

**Comment by SimonDarksideJ** [comment]
Which project are you seeing this on?  Just double checked my local source and it was fine.
Don't forget to do a clean and rebuild.

**Comment by SimonDarksideJ** [comment]
Tested against MonoGame 3.7 and working fine
