### ISSUE TITLE
Loading Song on MS Windows

### ISSUE THREAD

**Issue by Martin-Schultz** [MonoGame/MonoGame.Samples#42]
Hi,

I compiled the samples and erspecially focused on the platformer2d.
i kopied the content files to the corresponding directories, since i recieved exceptions stating, that the content could not be loaded as a non content file.

however i copied the raw assets into the directories as well and the sample works except for the music. xnb files and wav / ogg files are in the same folder, so i cannot explain why this does not work.

my configuration is xamarin studio on windows 10 and i compiled the windows x64 profile

**Comment by SimonDarksideJ** [comment]
Tested against the MonoGame 3.7 build without issue
