### ISSUE TITLE
.NET Core/Standard

### ISSUE THREAD

**Issue by grahamehorner** [MonoGame/MonoGame.Samples#44]
Please consider updating the samples with .net core/standard samples

**Comment by harry-cpp** [comment]
> .net core/standard samples

There is no official support for .net core/standard...

**Comment by SimonDarksideJ** [comment]
There is now :D will be covered as part of #50

**Comment by harry-cpp** [comment]
Ha, the irony of me commenting that and me adding the support for it XD

Ok, gonna close this one as the other one is tracking this better.
