### ISSUE TITLE
Updating MonoGame.Samples for 3.8

### ISSUE THREAD

**Issue by SimonDarksideJ** [MonoGame/MonoGame.Samples#50]
Starting a discussion to get a heads of agreement on a plan to update the samples to 3.8

My initial thoughts are as follows:

- [X] Review and close-out existing PR's for 3.7
- [X] Review any outstanding issues
- [X] Commit current examples to a 3.7 branch
- [X] Update develop branch samples to 3.8
- [X] Create an updated sample template using 3.8 pattern
- [X] Review new samples for 3.8

Weigh in below (before we start)

**Comment by SimonDarksideJ** [comment]
We should also incorporate feedback raised  in:
https://github.com/MonoGame/MonoGame/issues/7192

**Comment by harry-cpp** [comment]
I want to propose a new structure for the samples repo:
- Platformer2D
  - Platformer2D.Core
    - Platformer2D.Core.csproj - .NET Standard Library
  - Platformer2D.Linux/
    - Platformer2D.Linux.csproj
  - Platformer2D.Windows
    - Platformer2D.Windows.csproj
  - Platformer2D.Linux.sln
  - Platformer2D.Windows.sln
  - README.md
- SpaceWar
- NeoShooter
- README.md

**Comment by SimonDarksideJ** [comment]
I think it's a good idea to separate out the samples in to their own sln files. Not entirely sure about the separate lib, but I'll do some tests

**Comment by harry-cpp** [comment]
It's one of 2 standard ways for writing MG games for easy crossplatform. Another approach are shared projects, but MS has not really updated the dotnet tooling to work nicely with them, so I try to avoid them when not needed.

**Comment by SimonDarksideJ** [comment]
Samples updated to the new template @harry-cpp and working well. Even managed to make a template project which generates new projects too,

**Comment by SimonDarksideJ** [comment]
Completed, 3.7 samples archived to the 3.7 branch. Develop is now 3.8
