### ISSUE TITLE
.NET 5.0 compatibility

### ISSUE THREAD

**Issue by FyiurAmron** [MonoGame/MonoGame.Samples#53]
Currently, the samples simply ain't compatible with .NET 5.0 on regular OpenGL/DirectX Windows build due to .csproj settings, although the very code seems to be .NET 5.0-compliant.

**Comment by SimonDarksideJ** [comment]
Samples do need updating to 3.8.1, which is a work in progress

**Comment by SimonDarksideJ** [comment]
All samples have now been updated to 3.8.1 @FyiurAmron
