### ISSUE TITLE
NeonShooter Sample doesn't build with clean install of MonoGame 3.8.1

### ISSUE THREAD

**Issue by lilo-san** [MonoGame/MonoGame.Samples#61]
In my opinion this sample needs two things.
1. Provide instructions indicating any dependent runtimes needed to build the shaders.
2. Get updated to build using Mono 3.8.1

As a beginner using the platform it becomes unwieldy when I can't even build the official samples following the official documentation.

**Comment by SimonDarksideJ** [comment]
The samples have not been updated to 3.8.1 as yet, still to do.

**Comment by SimonDarksideJ** [comment]
Resolved with the update to 3.8.1, should work fine now @lilo-san
