### ISSUE TITLE
ShipGame: Only UI shows in game view on DX

### ISSUE THREAD

**Issue by SimonDarksideJ** [MonoGame/MonoGame.Samples#68]
DX Screenshot
![image](https://github.com/MonoGame/MonoGame.Samples/assets/1793042/4aa41313-ea53-4c66-b6be-e49e42f67b1c)

GL screenshot
![image](https://github.com/MonoGame/MonoGame.Samples/assets/1793042/2b4bd504-9d38-4d07-a309-e49344dbeaa2)

**Comment by NemoKradXNA** [comment]
Ill have a look.
