### ISSUE TITLE
ShipGame: Ships do not show on ship selection screen on DX

### ISSUE THREAD

**Issue by SimonDarksideJ** [MonoGame/MonoGame.Samples#69]
DX Screenshot
![image](https://github.com/MonoGame/MonoGame.Samples/assets/1793042/87d256b3-5732-467a-ad3d-4877802ede8c)

GL Screenshot
![image](https://github.com/MonoGame/MonoGame.Samples/assets/1793042/01dafbe9-4d74-438b-9d35-3c420f391bd2)

**Comment by NemoKradXNA** [comment]
Ill take a look.
