### ISSUE TITLE
ShipGame: Title screen does not animate on DX, but does on GL

### ISSUE THREAD

**Issue by SimonDarksideJ** [MonoGame/MonoGame.Samples#70]
DX Screenshot
![image](https://github.com/MonoGame/MonoGame.Samples/assets/1793042/a7d0e859-f0e4-4f48-b411-db0eabf52587)

GL Screenshot

https://github.com/MonoGame/MonoGame.Samples/assets/1793042/fab5143b-2279-480e-941c-7b4a24ee1ffe

**Comment by NemoKradXNA** [comment]
Ill take a look at this, forked and think I can see the issue. Will look at the other two too.
