### ISSUE TITLE
Use MonoGame ContentBuilder

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame.Samples#8]
We need to convert the sample to use the MonoGame content building tools.

**Comment by tomspilman** [comment]
@DDReaper - FYI.

**Comment by SimonDarksideJ** [comment]
Oh the ToDo list for the new develop branch.
First I'll have to get myself up to date with how the new system works.  Unless there are any other volunteers to help update the Platformer2D sample on the develop branch?

**Comment by tomspilman** [comment]
The important thing to know is that it is a command line tool.  See the following docs:

https://github.com/mono/MonoGame/wiki/MonoGame-Content-Builder

An example of a file for generating content would be:

```
/importer:TextureImporter
/processor:TextureProcessor
/processorParam:ColorKeyEnabled=false
/build:Textures\wood.png
/build:Textures\metal.png
/build:Textures\plastic.png
```

I think we would end up with one of these files with all the content for the sample.  We would then execute them from a batch file like so:

```
mgcb.exe /outputDir:bin/iOS /intermediateDir:obj/iOS /platform:iOS /rebuild /@:platformer2D.content
mgcb.exe /outputDir:bin/Linux /intermediateDir:obj/Linux /platform:Linux /rebuild /@:platformer2D.content
```

**Comment by tomspilman** [comment]
The first question is where will it get the "MGCB.exe" and dependent assemblies to build things with?

**Comment by nkast** [comment]
Interesting!

Some random  questions... 
Will MGCB and 2MGFX merge in the future?
Why the 2MGFX doesn't use the .XNB format as a wrapper?

Finding the various parameters could be hard. 
Could this be possible through MGCB in an interactive way? 
for example:
mgcb.exe   /Schema
/importer:[Importer]
/processor:[Processor]
/build:[filename]
etc...

mgcb.exe   /reference:"/myImporters"  /Schema:Importer
/TextureImporter
/SoundImporter
/MyImporter
etc...

mgcb.exe /processor:TextureProcessor /Schema:processorParam
/ColorKeyEnabled=[Boolean]
/GenerateMipmaps=[Boolean]
/ColorKeyColor=[Color]
/TextureFormat=[TextureFormat]
etc...

mgcb.exe /Schema:Boolean
/true
/false

mgcb.exe /Schema:TextureFormat
/Color
/DXT1
/DXT3
/Unchanged

**Comment by tomspilman** [comment]
> Will MGCB and 2MGFX merge in the future?

No they serve different purposes.

2MGFX is the stand alone effect compiler.  This is what we use to compile the stock effects which are embedded as resources into the MonoGame assembly.  These effects are loaded by passing their bytes to the `Effect` constructor.

MGCB is the content building tool which packages content for runtime.  Internally to MGCB it uses the 2MGFX code to convert effects to a runtime format and packages it into an .XNB like any other content.  These effects would be loaded via `ContentManager`.

> Finding the various parameters could be hard. 
> Could this be possible through MGCB in an interactive way? 

We're working on a better solution....

![pipeline](https://cloud.githubusercontent.com/assets/103522/2809447/a4b7f658-cd6f-11e3-9fe9-879bc7d783ee.png)

**Comment by nkast** [comment]
@tomspilman  WOW!
This looks good. I started working on something similar for my editor. Part of a bigger project, maybe I could release something If I turn it into a plugin.

So, MGCB can already pack  .MGFX files into XNB. I see what you mean, MGFX is a raw format that loads fast, no need to deal with XNB TypeLoaders, etc. 
So, MGCB can also parse .fx files into XNBs or works only with .mgfx? 
some possible senarios :
1) .mgfx --(wrap)--> .xnb
2) .mgfx --(copy)--> .mgfx
3) .fx      --(parse)--> .mgfx
4) .fx      --(parse+wrap)--> .xnb

**Comment by tomspilman** [comment]
> maybe I could release something If I turn it into a plugin.

We're adding a few more core features to the tool then we're going to push it to the `develop` branch.  At that point I hope others will help contribute fixes and improvements.

> MGFX is a raw format that loads fast, no need to deal with XNB TypeLoaders, etc. 

It is just different needs...  XNBs only load via the `ContentManager` and the stock effects in MonoGame don't load via the `ContentManager`.

**Comment by nkast** [comment]
It seems I am not able to produce a correct branch from MonoGame.Samples.  8-(
https://github.com/nkast/MonoGame.Samples/tree/tnc_Use_MG_ContentBuilder
It always brings in unrelated files, while the GitHub app shows it correctly.

Anyways, 
I played a little with MGCB, added two files under Platformer2D\Content,
https://github.com/nkast/MonoGame.Samples/blob/tnc_Use_MG_ContentBuilder/Platformer2D/Content/RebuildMGCB.bat
https://github.com/nkast/MonoGame.Samples/blob/tnc_Use_MG_ContentBuilder/Platformer2D/Content/Windows.Content

The problems I found 
-I don't know how to tell MGCB to just copy the Content\Levels\ text files to the output directory. 
-The  \Content\Fonts\Hud.spritefont throw errors.

Once I copied the produced files into the current content directory, everything worked!
So, I need a way to tell MGCB to just copy the source files without any processing. Maybe use /Copy instead of /Build? or some combination of importer/processor.
Once I have this, I could just place the Hud.xnb produced by XNA along with Hud.spritefont, and tell MGCB to copy the .xnb , until the issue with fonts is resolved. This can be done for all fileformats currently unsoported and remove the old xna content processor.

**Comment by SimonDarksideJ** [comment]
The new samples have been merged now into the develop branch, just do a fetch against the primary repo (not your fork), then do a fetch to expose the new branch.
Then do a switch/checkout to the new branch and pull.  You should get the current state of the branch then.

As for the content errors, can you not reference them from the project, or is the builder putting the .xnb files in the same folder as the source content it'self and stopping you from using the global method you mentioned

**Comment by tomspilman** [comment]
> I don't know how to tell MGCB to just copy the 
> Content\Levels\ text files to the output directory. 

`/copy:Content\Levels\level.txt` will work, just haven't added it to the docs.

> The \Content\Fonts\Hud.spritefont throw errors.

 What error did you get?  Also what platform where you building under?

**Comment by danzel** [comment]
I've just built for iOS using the existing content code in this repo. The font ended up with a 128x144 size texture, which doesn't work as it is Pvrtc compressed.

Edit: It throws an error on loading after trying to GL.CompressedTexImage2D load it

**Comment by tomspilman** [comment]
> The font ended up with a 128x144 size texture, which 
> doesn't work as it is Pvrtc compressed,

There are two possible paths for a fix here. 
- Don't PVRTC compress the font textures.
- Force the texture size up to the next power of two.

I suspect the first one is best as it is simplest and fixes complaints about the compression artifacts on the fonts.

**Comment by danzel** [comment]
The first is probably the best as you say.
Weird that we've never ran in to this bug before, maybe something we've broken recently?

**Comment by tomspilman** [comment]
Very possible something was broken.

It would be nice to switch to `Alpha8` for sprite fonts (see https://github.com/mono/MonoGame/issues/2026) in the process.  But it has a bunch of complications like needing shader changes to make things work.

**Comment by SimonDarksideJ** [comment]
So @tomspilman is the new content process in a good state yet to build all the content for the samples, or at least the Platformer project to begin with?

**Comment by tomspilman** [comment]
You should start to move the samples over to it.  If you run into a problem, report the bug and lets fix it.  The more we start to use the new content pipeline the more issues we will be forced to fix.

**Comment by SimonDarksideJ** [comment]
Fair enough, I'll put it on the todo list along with the doc tasks.  Thanks

**Comment by tomspilman** [comment]
@DDReaper - Any update on this?

**Comment by SimonDarksideJ** [comment]
Not had a chance to focus on this yet, other commitments have pulled me away for the moment.

**Comment by SimonDarksideJ** [comment]
Right, just to let everyone know I've started work on this.  Already got the NeonShooter and Platformer2D samples updated for WIndowsGL.  
SpaceWar couldn't be updated as it caused LOADS of fbx import errors.

**Comment by tomspilman** [comment]
> SpaceWar couldn't be updated as it caused LOADS of fbx import errors.

Good...  enter an issue for this and we'll start working thru them.

**Comment by theZMan** [comment]
If its that ASSIMP doesn't support the FBX version then we need to get all the assets reimported in a newer FBX format. Problem with this is that you have to replicate the export options that were chosen when they were originally imported!

Brian Peek told me that using the VS12/13 graphics tools to open and then resave FBX files might work  but I've not had a chance to try it yet.

**Comment by tomspilman** [comment]
> Brian Peek told me that using the VS12/13 graphics tools to open and then resave FBX files might work 

I've had luck with that myself at times.

**Comment by SimonDarksideJ** [comment]
Ok, I'll update spacewar again and if nessasary leave it broken since it's the dev branch.  Then it can be used for testing.
I'll also try editing the FBX's in 2013 (got upd 4 so I should have all the tools) and see if that helps any of them.

Should have the rest of the projects done in the next few days.

Once committed, I'll have a go at drafting some docs, especially an upgrade guide for anyone wishing to update to the Dev release.

**Comment by SimonDarksideJ** [comment]
Right, updated SpaceWar again.
Loading the fbx models in to VS2013 and resaving them (have to actually use SaveAs to overwrite) sorted the model issue.  There was an additional issue where the textures wern't being picked up.  Took me a while how to edit the texture paths but got there in the end (although it doesn't support relative paths, so that may be an issue, might be easier to use another model format)

Last issue is that the XACT file can't be imported.  Ideas?

Moving on to the rest now, converting as I go :dancer:

**Comment by tomspilman** [comment]
> Last issue is that the XACT file can't be imported. Ideas?

Well XACT is not content in the same sense.  XACT is its own binary format that isn't processed via the content pipeline.  You just need to add it like any other data file.

**Comment by SimonDarksideJ** [comment]
committed PR #30 to update all existing projects to use the new MGCB tool

Few outstanding build issues which are highlighted in the commit, introduced by the latest dev release and the MGCB tool

**Comment by SimonDarksideJ** [comment]
@tomspilman I think this issue can be closed now.  Need to work on separate issues for the specific update elements as required, aka SpaceWar.
I think we need to look for an alternate 3D sample.  Will revisit this now the 3.3 release is out.
